package me.vebbo.android.utils;

public class Constant {

    //public static final String URL = "http://192.xxx.xx.xx:xxxx";
    public static final String URL = "https://vebbo.herokuapp.com/";

    public static final String USERNAME = "userName";
    public static final String LOCATION = "location";
    public static final String FACEBOOK = "facebook";
    public static final String INSTAGRAM = "instagram";
    public static final String TWITTER = "twitter";
    public static final String WEBSITE = "website";
    public static final String BIO = "bio";
    public static final String IMAGE = "image";
    public static final String SUSPENSION = "suspension";
    public static final String FONT = "fonts/ubuntu.regular.ttf";
    public static final String EMAIL = "email";
    public static final String CARD_NAME = "cardName";
    public static final String CARD_NUMBER = "cardNum";
    public static final String MONTH = "month";
    public static final String YEAR = "year";
    public static final String STREAM = "stream";
    public static final String TAG = "tag";
    public static final String TOKEN = "token";
    public static final String NOTE = "note";
    public static final String CONTENT = "content";
    public static final String USER_ID = "userId";
    public static final String UTC = "utc";
    public static final String MAIL = "stackdriveinc@gmail.com";
    public static final String ATTR_FONT_NAME = "fonts/";
    public static final String COMMENT_TEXT = "comment";
    public static final String MAIL_TYPE = "text/plain";
    public static final String MAIL_TO = "mailto:";
    public static final String CAMERA = "camera";
    public static final String AUDIO = "audio";
    public static final String COMMENT = "comment";
    public static final String UPDATE = "update";
    public static final String FLAG = "flag";
    public static final String ONLINE = "online";
    public static final String LIVE = "live";
    public static final String TIMER = "timer";
    public static final String VALUES = "values";
    public static final String END = "end";
    public static final String SOCKET_ID = "socketId";
    public static final String DATA = "data";
    public static final String IS_BACK = "isBack";
    public static final String ROTATION = "rotation";
    public static final String PLATFORM = "platform";
    public static final String ENV = "android";
    public static final String DOLLAR = "dollar";
    public static final String NAIRA = "naira";
    public static final String FLAG_UTC = "flagUTC";
    public static final String STATE = "state";
    public static final String STREAM_LIVE = "isLive";
    public static final String HELP = "isHelp";
    public static final String SELECTED = "selected";
    public static final String CLAPS = "claps";
    public static final String STORE = "store";
    public static final String OPT1 = "opt1";
    public static final String OPT2 = "opt2";
    public static final String OPT3 = "opt3";
    public static final String CHECK = "check";
    public static final String EXISTS = "exists";
    public static final String PROMPT = "prompt";
}
